---
chdir: /home/ubuntu/contact/current
environment: production
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 30
socket: /var/run/thin/contact.sock
daemonize: true
servers: 5
